default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

default_shard: &default_shard
  <<: *default
  schema_dump: false

development:
  primary:
    <<: *default
    database: 'primary_development'
  secondary:
    <<: *default_shard
    database: 'secondary_development'

test:
  <<: *default
  database: rails_demo_test

production:
  <<: *default
  database: rails_demo_production
  username: rails_demo
  password: <%= ENV["RAILS_DEMO_DATABASE_PASSWORD"] %>
